"""Eliminar columna foto_ruta de Socio

Revision ID: 7ce8d67e95bd
Revises: e18a65cbefc6
Create Date: 2024-05-16 18:34:59.769949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce8d67e95bd'
down_revision = 'e18a65cbefc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('foto_ruta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_ruta', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
