"""Modificar tabla Asistencia para relacinarse con Socio y Entrenador

Revision ID: befad5021c6e
Revises: 7ce8d67e95bd
Create Date: 2024-05-16 18:48:14.464553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befad5021c6e'
down_revision = '7ce8d67e95bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entrenador_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('asistencia_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'socio', ['socio_id'], ['id'])
        batch_op.create_foreign_key(None, 'entrenador', ['entrenador_id'], ['id'])
        batch_op.drop_column('tipo_usuario')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_usuario', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asistencia_usuario_id_fkey', 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('entrenador_id')
        batch_op.drop_column('socio_id')

    # ### end Alembic commands ###
