"""Modificar tabla Socio agregar columna Apellido

Revision ID: c07c3c3a8646
Revises: befad5021c6e
Create Date: 2024-05-16 19:59:05.733580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07c3c3a8646'
down_revision = 'befad5021c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
