"""Agregar tabla RegistroRostros

Revision ID: e18a65cbefc6
Revises: d9a41be5cbb4
Create Date: 2024-05-16 18:32:15.087812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18a65cbefc6'
down_revision = 'd9a41be5cbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_rostros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=True),
    sa.Column('entrenador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ruta', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenador.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_rostros')
    # ### end Alembic commands ###
